# Generated by Django 5.0.6 on 2024-07-13 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ID_tipo_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.tipousuario'),
        ),
    ]
